# Generated by Django 5.2.7 on 2025-10-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requisicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.CharField(choices=[('ON_DEMAND', 'On Demand'), ('POLLO_BRUJO', 'Pollo Brujo'), ('FIJOS', 'Proyectos Fijos')], max_length=20)),
                ('cantidad', models.PositiveIntegerField()),
                ('justificacion', models.TextField()),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=10)),
            ],
        ),
    ]
