# Generated by Django 5.2.7 on 2025-10-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('dpi', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('proyecto', models.CharField(choices=[('ON_DEMAND', 'On Demand'), ('POLLO_BRUJO', 'Pollo Brujo'), ('FIJOS', 'Proyectos Fijos')], max_length=20)),
                ('estado', models.CharField(choices=[('ALTA', 'Alta'), ('BAJA', 'Baja')], default='ALTA', max_length=10)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
    ]
